name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('api/.env') || copy('api/.env.example', 'api/.env');"
      - name: Install Dependencies
        run: cd api && composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: cd api && php artisan key:generate
      - name: Directory Permissions
        run: cd api && chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          cd api && 
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: cd api && vendor/bin/phpunit
